ogijima/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'ogijima'
urlpatterns = [
    # 延期になりましたっていう記事にすればいいのに消しちゃったから、リダイレクトように強引に作成
    path('work_detail/17',views.work_detail_redirect,name="work_detail_redirect"),

    path('',views.top,name="top"),
    path('aboutus',views.aboutus,name="aboutus"),
    path('works',views.works,name="works"),
    path('planed_works',views.planed_works,name="planed_works"),
    path('held_works',views.held_works,name="held_works"),
    path('work_detail/<int:work_id>',views.work_detail,name="work_detail"),
    path('reports',views.reports,name="reports"),
    path('blog_detail/<int:blog_id>',views.blog_detail,name="blog_detail"),
    path('profile',views.profile,name="profile"),
    path('information',views.information,name="information"),
    path('arts',views.arts,name="arts"),
    path('art_detail/<int:id>',views.art_detail,name="art_detail"),
    path('restaurants',views.restaurants,name="restaurants"),
    path('restaurant_detail/<int:id>',views.restaurant_detail,name="restaurant_detail"),
    path('hotels',views.hotels,name="hotels"),
    path('hotel_detail/<int:id>',views.hotel_detail,name="hotel_detail"),
    path('restaurant_and_hotel_detail/<int:id>',views.restaurant_and_hotel_detail,name="restaurant_and_hotel_detail"),
    path('cats',views.cats,name="cats"),
    path('cat_detail/<int:id>',views.cat_detail,name="cat_detail"),
    path('aikien_service',views.aikien_service,name="aikien_service"),
    path('aikien_service_calender_reload',views.aikien_service_calender_reload,name="aikien_service_calender_reload"),
    path('gallery',views.gallery,name="gallery"),
    path('notifications',views.notifications,name="notifications"),
    path('contact',views.contact,name="contact"),
    path('contact_completed/<str:email>',views.contact_completed,name="contact_completed"),
    path('sponsor',views.sponsor,name="sponsor"),
    path('privacypolicy',views.privacypolicy,name="privacypolicy"),

    # 営業資料用サンプル
    path('restaurants_sample',views.restaurants_sample,name="restaurants_sample"),
    path('restaurant_detail_sample/<int:id>',views.restaurant_detail_sample,name="restaurant_detail_sample"),
]

ogijima_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse
# from django.conf.urls import url
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from ogijima.models import *
from django.views.generic import TemplateView
from django.shortcuts import resolve_url

class StaticSitemap(Sitemap):
    priority = 0.6
    changefreq = "never"

    def items(self):
        return [
            "ogijima:top",
            "ogijima:aboutus",
            "ogijima:works",
            "ogijima:planed_works",
            "ogijima:held_works",
            "ogijima:reports",
            "ogijima:profile",
            "ogijima:information",
            "ogijima:arts",
            "ogijima:restaurants",
            "ogijima:hotels",
            "ogijima:cats",
            "ogijima:gallery",
            "ogijima:notifications",
            "ogijima:contact",
            "ogijima:sponsor",
            "ogijima:privacypolicy",
            "ogijima:aikien_service",
        ]

    def location(self, obj):
        return reverse(obj)

class WorkSitemap(Sitemap):
    priority = 0.5

    def items(self):
        return Work.objects.order_by("-date")

    def location(self, obj):
        return resolve_url('ogijima:work_detail', work_id=obj.pk)

class BlogSitemap(Sitemap):
    priority = 0.5

    def items(self):
        return Blog.objects.order_by("-date")

    def location(self, obj):
        return resolve_url('ogijima:blog_detail', blog_id=obj.pk)

sitemaps = {
    'static': StaticSitemap,
    'work': WorkSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},  name='sitemap'),
    path('',include('ogijima.urls',namespace='ogijima')),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    # re_path(r'^robots\.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path("robots.txt/", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ogijima/forms.py
from django import forms
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail, EmailMessage
from django.http import HttpResponse
from django.core.validators import FileExtensionValidator
from django.core.files.storage import default_storage
from .models import *

class ContactForm(forms.Form):
    name = forms.CharField(
        label='名前',
        max_length=100,
        required=True,
    )
    email = forms.EmailField(
        label='メールアドレス',
        max_length=100,
        required=True,
        widget=forms.EmailInput({
            "placeholder": "example@example.com",
        }),
    )
    title = forms.CharField(
        label='件名',
        max_length=200,
        required=True,
    )
    text = forms.CharField(
        label='本文',
        max_length=1000,
        required=True,
        widget=forms.Textarea({
            "rows": 3,
            "cols": "",
        }),
    )

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        text = self.cleaned_data['text']
        subject = "【男木島名物倉庫『あいきえん』】お問い合わせ内容の確認"
        message = """※このメールはシステムからの自動返信です。

{name} 様
お問い合わせいただきありがとうございます。
以下の内容で承りました。

━━━━━━□■□　お問い合わせ内容　□■□━━━━━━
お名前 ： {name}

メールアドレス ： {email}

件名 ： {title}

お問い合わせ内容：
{text}
━━━━━━━━━━━━━━━━━━━━━━━━━━


担当の者より、数日で返信させていただきますので、今しばらくお待ちくださいませ。


※このメールは送信専用です。このメールにご返信いただいても、お返しすることができませんので、ご了承ください。
""".format(name=name, email=email, title=title, text=text)
        from_email = '男木島名物倉庫『あいきえん』お問い合わせ <{email}>'.format(email=settings.EMAIL_HOST_USER)
        recipient_list = ['{email}'.format(email=email)]
        bcc = ['{email}'.format(email=settings.EMAIL_HOST_USER),'ogijima.pj.hp@gmail.com']
        try:
            # send_mail(subject, message, from_email, recipient_list, bcc)
            email = EmailMessage(subject, message, from_email, recipient_list, bcc)
            email.send()
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")
    def return_email(self):
        return self.cleaned_data['email']

class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application_contact
        fields = '__all__'

ogijima/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.core.mail import BadHeaderError, send_mail, EmailMessage
from ogijima.forms import ContactForm, ApplicationForm
from .models import *
from .ignore import *
from markdown import markdown
import re
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime, calendar
from dateutil.relativedelta import relativedelta

import urllib
import json

from django.contrib import messages

def get_first_date(dt):
    return dt.replace(day=1)
def get_last_date(dt):
    return dt.replace(day=calendar.monthrange(dt.year, dt.month)[1])

def top(request):
    all_works = Work.objects.all().order_by("-work_start_date")
    today = timezone.now().date()
    now_works = Work.objects.filter(work_start_date__lte=today,work_end_date__gte=today).all()
    future_works = all_works.filter(work_start_date__gt=today)
    p = re.compile(r"<[^>]*?>")
    if now_works:
        now_works = now_works.order_by("work_start_date")
        for now_work in now_works:
            now_work.content = p.sub("", markdown(now_work.content))
    if future_works:
        future_works = future_works.order_by("work_start_date")
        future_work = future_works[0]
        future_work.content = p.sub("", markdown(future_work.content))
    else:
        future_work = []
    
    arts = Art.objects.all()
    restaurants = Restaurant.objects.all()
    hotels = Hotel.objects.all()
    cats = Cat.objects.all()
    restaurant_and_hotel = Restaurant_and_hotel.objects.all()

    slideshow_pc = Slideshow_pc.objects.all().order_by("order")
    slideshow_mobile = Slideshow_mobile.objects.all().order_by("order")

    notifications = Notification.objects.all().order_by("-date")[0:5]

    params = {
        'now_works': now_works,
        'future_work': future_work,
        'arts': arts,
        'restaurants': restaurants,
        'hotels': hotels,
        'cats': cats,
        'restaurant_and_hotel': restaurant_and_hotel,
        'slideshow_pc': slideshow_pc,
        'slideshow_mobile': slideshow_mobile,
        'notifications': notifications,
    }
    return render(request,'top.html', params)

def aboutus(request):
    return render(request,'aboutus.html')

def works(request):
    all_works = Work.objects.all().order_by("-work_start_date")
    today = timezone.now().date()
    now_works = Work.objects.filter(work_start_date__lte=today,work_end_date__gte=today).all()
    # if(now_works.count()==0):
    #     now_works = all_works.filter(work_start_date__lte=today).first()
    #     if(now_works==None):
    #         now_works_date = today
    #     else:
    #         now_works_date = now_works.work_start_date
    # try:
    #     now_works = now_works.order_by("work_start_date")
    #     p = re.compile(r"<[^>]*?>")
    #     for work in now_works:
    #         work.content = p.sub("", markdown(work.content))
    # except:
    #     print()
    now_works = now_works.order_by("work_start_date")
    p = re.compile(r"<[^>]*?>")
    for work in now_works:
        work.content = p.sub("", markdown(work.content))
    params = {
        'now_works':now_works,
    }
    return render(request,'works.html',params)

def planed_works(request):
    today = timezone.now().date()
    future_works = Work.objects.all().filter(work_end_date__gt=today)
    future_works = future_works.order_by("work_start_date")
    p = re.compile(r"<[^>]*?>")
    for work in future_works:
        work.content = p.sub("", markdown(work.content))
    # paginator = Paginator(future_works, 10)
    paginator = Paginator(future_works, 5)
    page = request.GET.get('page', 1)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)
    params = {
        'pages': pages,
    }
    return render(request,'planed_works.html', params)

def held_works(request):
    today = timezone.now().date()
    past_works = Work.objects.all().filter(work_end_date__lt=today)
    past_works = past_works.order_by("-work_start_date")
    p = re.compile(r"<[^>]*?>")
    for work in past_works:
        work.content = p.sub("", markdown(work.content))
    # paginator = Paginator(past_works, 10)
    paginator = Paginator(past_works, 5)
    page = request.GET.get('page', 1)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)
    params = {
        'pages': pages,
    }
    return render(request,'held_works.html', params)

def work_detail(request,work_id):
    work = Work.objects.get(pk=work_id)
    work.content = markdown(work.content)
    worklist = Work.objects.order_by('work_start_date')
    idx = list(map(lambda x:x.pk, worklist)).index(work_id)
    if idx==0:
        prev_id = -1
    else:
        prev_id = worklist[idx-1].pk
    if idx==len(worklist)-1:
        next_id  = -1
    else:
        next_id = worklist[idx+1].pk
    params = {
        'work':work,
        'prev_id':prev_id,
        'next_id':next_id
    }
    return render(request,'work_detail.html',params)

def reports(request):
    blog = Blog.objects.all().order_by('-date')
    paginator = Paginator(blog, 5)
    # paginator = Paginator(blog, 10)
    page = request.GET.get('page', 1)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(1)
    p = re.compile(r"<[^>]*?>")
    for blog in pages:
        blog.content = p.sub("", markdown(blog.content))
    params = {
        'pages': pages,
    }
    return render(request,'reports.html', params)

def blog_detail(request,blog_id):
    blog = Blog.objects.get(pk=blog_id)
    blog.content = markdown(blog.content)
    bloglist = Blog.objects.order_by('date')
    idx = list(map(lambda x:x.pk, bloglist)).index(blog_id)
    if idx==0:
        prev_id = -1
    else:
        prev_id = bloglist[idx-1].pk
    if idx==len(bloglist)-1:
        next_id  = -1
    else:
        next_id = bloglist[idx+1].pk
    params = {
        'blog':blog,
        'prev_id':prev_id,
        'next_id':next_id
    }
    return render(request,'blog_detail.html',params)

def profile(request):
    profile = Profile.objects.all().order_by('order')
    return render(request,'profile.html',{'profile':profile})

def information(request):
    arts = Art.objects.all()
    restaurants = Restaurant.objects.all()
    hotels = Hotel.objects.all()
    cats = Cat.objects.all()
    restaurant_and_hotel = Restaurant_and_hotel.objects.all()
    params = {
        'arts': arts,
        'restaurants': restaurants,
        'hotels': hotels,
        'cats': cats,
        'restaurant_and_hotel': restaurant_and_hotel,
    }
    return render(request,'information.html', params)

def arts(request):
    art = Art.objects.all().order_by('id')
    params = {
        'art': art,
    }
    return render(request,'arts.html', params)

def art_detail(request, id):
    art = Art.objects.get(pk=id)
    art.document = markdown(art.document)
    return render(request,'art_detail.html',{'art':art})

def aikien_service(request):
    sitekey = GOOGLE_RECAPTCHA_SITE_KEY

    today = datetime.datetime.today().date()
    thisMonthFirstDate = get_first_date(today)
    thisMonthLastDate = get_last_date(today)
    eventlist = Work_for_calender.objects.filter(work_start_date__lte=thisMonthLastDate,work_end_date__gte=thisMonthFirstDate).all()
    dayList = []
    day = 1
    while True:
        place_count = 0
        thisDay = thisMonthFirstDate + datetime.timedelta(days=day - 1)
        if thisDay > thisMonthLastDate:
            break
        for event in eventlist:
            if thisDay >= event.work_start_date and thisDay <= event.work_end_date:
                if event.place == 0:
                    place_count += 10
                else:
                    place_count += event.place
        if place_count > 2:
            place_count = 10
        dayList.append([day, place_count])
        day += 1

    if request.method == 'POST':
        form = ApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ''' End reCAPTCHA validation '''

            if result['success']:
                # form.send_email()
                # email = form.return_email()
                # return redirect('ogijima:contact_completed', email)

                postdata = Application_contact(
                    name = request.POST['name'],
                    mail = request.POST['mail'],
                    content = request.POST['content'],
                    application_file = request.FILES['application_file'],
                
                )
                postdata.save()
                name = request.POST['name']
                email = request.POST['mail']
                text = request.POST['content']
                subject = "【男木島名物倉庫『あいきえん』】アートギャラリーお申込内容の確認"
                message = """※このメールはシステムからの自動返信です。

{name} 様
アートギャラリーのご利用申込いただきありがとうございます。
以下の内容で承りました。ご確認よろしくお願いします。
添付いただいたファイルも添付しておりますので、併せてご確認ください。

━━━━━━□■□　申込内容　□■□━━━━━━
お名前 ： {name}

メールアドレス ： {email}

申込内容：
{text}
━━━━━━━━━━━━━━━━━━━━━━━━━━


担当の者より、数日で返信させていただきますので、今しばらくお待ちくださいませ。


※このメールは送信専用です。このメールにご返信いただいても、お返しすることができませんので、ご了承ください。

ogijima/templates/503.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'css/errorpage.css' %}">
{% endblock %}

{% block main_panel %}
<h1>503 Service Unavailable</h1>
<p>サーバーが混雑しており、一時的にアクセスできません。お手数をおかけしますが、再度時間をおいてアクセスしてください。</p>
<a class="return-button" href="{% url 'ogijima:top' %}">トップページへ戻る</a>
{% endblock %}

ogijima/templates/cats.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
<!-- <link rel="stylesheet" href="https://aikien.s3.ap-northeast-3.amazonaws.com/css/information_list.css"> -->
<link rel="stylesheet" href="{% static 'css/information_list.css' %}">
{% endblock %}

{% block main_panel %}
<h1 class="pagetitle">島猫紹介</h1>
<div class="list__wrapper">
    {% for cat in cat %}
    <a href="{% url 'ogijima:cat_detail' cat.id %}">
        <img src="{{ cat.thumbnail }}">
        <h5>{{ cat.name }}</h5>
    </a>
    {% endfor %}
</div>

<!-- ここからページネーション -->
{% if pages.has_other_pages %}
<nav class="pagination__nav">
    <ul class="pagination">
        {% if pages.has_previous %}
        <li>
            <a class="page-link text-primary d-inline-block" href="?page={{ pages.previous_page_number }}">
                前<span class="pagination__mobile-delete">のページ</span>へ
            </a>
        </li>
        {% else %}
        <li class="disabled">
            <p class="pagination__disabled-prev">
                前<span class="pagination__mobile-delete">のページ</span>へ
            </p>
        </li>
        {% endif %}

        {% if pages.has_previous %}
        {% if pages.previous_page_number != 1 %}
        <li>
            <a href="?page=1">1</a>
        </li>
        <li>…</li>
        {% endif %}
        <li>
            <a href="?page={{ pages.previous_page_number }}">
                {{ pages.previous_page_number }}
            </a>
        </li>
        {% endif %}
        <li class="disabled">
            <p class="pagination__disabled">{{ pages.number }}</p>
        </li>
        {% if pages.has_next %}
        <li>
            <a href="?page={{ pages.next_page_number }}">
                {{ pages.next_page_number }}
            </a>
        </li>
        {% if pages.next_page_number != pages.paginator.num_pages %}
        <li>…</li>
        <li>
            <a href="?page={{ pages.paginator.num_pages }}">
                {{ pages.paginator.num_pages }}
            </a>
        </li>
        {% endif %}
        {% endif %}
        {% if pages.has_next %}
        <li>
            <a href="?page={{ pages.next_page_number }}">
                次<span class="pagination__mobile-delete">のページ</span>へ
            </a>
        </li>
        {% else %}
        <li class="disabled">
            <p class="pagination__disabled-next">次<span class="pagination__mobile-delete">のページ</span>へ</p>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
<!-- ここまでページネーション -->

<div id="information-list" class="information-list">
    <a class="information-list-button" href="{% url 'ogijima:arts' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_art_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_art_2.svg' %}">
        <span>アート紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:restaurants' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_restaurant_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_restaurant_2.svg' %}">
        <span>飲食店紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:hotels' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_hotel_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_hotel_2.svg' %}">
        <span>宿泊施設紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:cats' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_cat_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_cat_2.svg' %}">
        <span>島猫紹介</span>
    </a>
</div>

{% endblock %}

{% block extra_js %}
{% endblock %}

ogijima/templates/hotels.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
<!-- <link rel="stylesheet" href="https://aikien.s3.ap-northeast-3.amazonaws.com/css/information_list.css"> -->
<link rel="stylesheet" href="{% static 'css/information_list.css' %}">
{% endblock %}

{% block main_panel %}
<h1 class="pagetitle">宿泊施設</h1>
<div class="list__wrapper">
    {% for hotel in hotel %}
    <a href="{% url 'ogijima:hotel_detail' hotel.id %}">
        <img src="{{ hotel.thumbnail }}">
        <h5>{{ hotel.name }}</h5>
    </a>
    {% endfor %}
    {% for restaurant_and_hotel in restaurant_and_hotel %}
    <a href="{% url 'ogijima:restaurant_and_hotel_detail' restaurant_and_hotel.id %}">
        <img src="{{ restaurant_and_hotel.thumbnail }}">
        <h5>{{ restaurant_and_hotel.name }}</h5>
    </a>
    {% endfor %}
</div>

<div id="information-list" class="information-list">
    <a class="information-list-button" href="{% url 'ogijima:arts' %}">
        <img src="{% static 'image/icon/ogi_hp_icon_art_2.svg' %}">
        <span>アート紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:restaurants' %}">
        <img src="{% static 'image/icon/ogi_hp_icon_restaurant_2.svg' %}">
        <span>飲食店紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:hotels' %}">
        <img src="{% static 'image/icon/ogi_hp_icon_hotel_2.svg' %}">
        <span>宿泊施設紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:cats' %}">
        <img src="{% static 'image/icon/ogi_hp_icon_cat_2.svg' %}">
        <span>島猫紹介</span>
    </a>
</div>

{% endblock %}

{% block extra_js %}
{% endblock %}

ogijima/templates/restaurants_sample.html
{% extends 'base.html' %}
{% load static %}

{% block extra_style %}
<!-- <link rel="stylesheet" href="https://aikien.s3.ap-northeast-3.amazonaws.com/css/information_list.css"> -->
<link rel="stylesheet" href="{% static 'css/information_list.css' %}">
{% endblock %}

{% block main_panel %}
<h1 class="pagetitle">飲食店</h1>
<div class="list__wrapper">
    {% for restaurant in pages %}
    <a href="{% url 'ogijima:restaurant_detail_sample' restaurant.id %}">
        <img src="{{ restaurant.thumbnail }}">
        <h5>{{ restaurant.name }}</h5>
    </a>
    {% endfor %}
</div>

<!-- ここからページネーション -->
{% if pages.has_other_pages %}
<nav class="pagination__nav">
    <ul class="pagination">
        {% if pages.has_previous %}
        <li>
            <a class="page-link text-primary d-inline-block" href="?page={{ pages.previous_page_number }}">
                前<span class="pagination__mobile-delete">のページ</span>へ
            </a>
        </li>
        {% else %}
        <li class="disabled">
            <p class="pagination__disabled-prev">
                前<span class="pagination__mobile-delete">のページ</span>へ
            </p>
        </li>
        {% endif %}

        {% if pages.has_previous %}
        {% if pages.previous_page_number != 1 %}
        <li>
            <a href="?page=1">1</a>
        </li>
        <li>…</li>
        {% endif %}
        <li>
            <a href="?page={{ pages.previous_page_number }}">
                {{ pages.previous_page_number }}
            </a>
        </li>
        {% endif %}
        <li class="disabled">
            <p class="pagination__disabled">{{ pages.number }}</p>
        </li>
        {% if pages.has_next %}
        <li>
            <a href="?page={{ pages.next_page_number }}">
                {{ pages.next_page_number }}
            </a>
        </li>
        {% if pages.next_page_number != pages.paginator.num_pages %}
        <li>…</li>
        <li>
            <a href="?page={{ pages.paginator.num_pages }}">
                {{ pages.paginator.num_pages }}
            </a>
        </li>
        {% endif %}
        {% endif %}
        {% if pages.has_next %}
        <li>
            <a href="?page={{ pages.next_page_number }}">
                次<span class="pagination__mobile-delete">のページ</span>へ
            </a>
        </li>
        {% else %}
        <li class="disabled">
            <p class="pagination__disabled-next">次<span class="pagination__mobile-delete">のページ</span>へ</p>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
<!-- ここまでページネーション -->

<div id="information-list" class="information-list">
    <a class="information-list-button" href="{% url 'ogijima:arts' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_art_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_art_2.svg' %}">
        <span>アート紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:restaurants' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_restaurant_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_restaurant_2.svg' %}">
        <span>飲食店紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:hotels' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_hotel_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_hotel_2.svg' %}">
        <span>宿泊施設紹介</span>
    </a>
    <a class="information-list-button" href="{% url 'ogijima:cats' %}">
        <!-- <img src="https://aikien.s3.ap-northeast-3.amazonaws.com/image/icon/ogi_hp_icon_cat_2.svg"> -->
        <img src="{% static 'image/icon/ogi_hp_icon_cat_2.svg' %}">
        <span>島猫紹介</span>
    </a>
</div>

{% endblock %}

{% block extra_js %}
{% endblock %}